version = 0.1
[default.deploy.parameters]
stack_name = "image-generator-20"
resolve_s3 = true
s3_prefix = "image-generator-20"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
