AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Couch-explorer

  Sample SAM Template for Couch-explorer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ImageGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8  
      CodeUri: image_generator/   
      Timeout: 20
      Environment:
        Variables:
          S3_BUCKET_NAME: "pgr301-couch-explorers"
          BUCKET_NUMBER: "20"
      Policies:
        - S3WritePolicy:
            BucketName: "pgr301-couch-explorers"
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"
      Events:
        ApiPostEvent:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"
