name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy SAM Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Debug Git Remote
        run: git remote -v

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install AWS CLI and SAM CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli unzip
          curl -sSL https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam-cli.zip
          unzip sam-cli.zip -d sam-installation
          sudo ./sam-installation/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name my-sam-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}
